name: 'java'

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: '0 */1 * * *'

on: 
  repository_dispatch:
    types:
      - webhook

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Debug Session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - name: 'run2'
        run: java -jar bikatask-0.0.1-SNAPSHOT.jar

concurrency:
  group: ${{ github.head_ref || github.ref_name }}  - hello world
  cancel-in-progress: true
