name: 'java'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  auto_renew:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: 'run2'
        run: java -jar bikatask-0.0.1-SNAPSHOT.jar
